# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: esad
dist: ./dist
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  ignore:
    - goos: darwin
      goarch: 386
archives:
-
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: '{{ .ProjectName }}_{{ .Version }}'
