name: Build and Test Anomaly detection
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:

  Build-ad:
    strategy:
      matrix:
        java: [14]

    name: Build and Test Anomaly detection Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # dependencies: OpenSearch
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: '821c44c440706e769b3d41c8ffce25282a72f3fb'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal -Dbuild.version_qualifier=alpha1 -Dbuild.snapshot=false

      # dependencies: common-utils
      - name: Checkout common-utils
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/common-utils'
          path: common-utils
      - name: Build common-utils
        working-directory: ./common-utils
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-alpha1

      # dependencies: job-scheduler
      - name: Checkout job-scheduler
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/job-scheduler'
          path: job-scheduler
      - name: Build job-scheduler
        working-directory: ./job-scheduler
        run: ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-alpha1 -Dbuild.snapshot=false

      # anomaly-detection
      - name: Checkout AD
        uses: actions/checkout@v2

      - name: Build and Run Tests
        run: |
          ./gradlew build -Dopensearch.version=1.0.0-alpha1

      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal -Dopensearch.version=1.0.0-alpha1

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: plugin
